import dynamic from "next/dynamic";
import Head from "next/head";
import CircularComponent from "../components/CircularComponent";
import LinearComponent from "../components/LinearComponent";

const Home = dynamic(
  () =>
    Promise.resolve(() => {
      return (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            <CircularComponent />
            <LinearComponent />
          </main>
        </>
      );
    }),
  { ssr: false }
);

export default Home;
